apiVersion: v1
kind: Service
metadata:
  name: kustomize-pythonsimple
  namespace: pythonsimple
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: kustomize-pythonsimple
