apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- pgsql-deployment.yaml
- pgsql-svc.yaml
- pgsql-pgdata-pvc.yaml
# - ingress.yaml

namespace: pgsql
