apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pgdata-pvc
  namespace: pgsql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
